const app = require('../app.js')
const User = require('../model/user.js')
const initTables = require('../data/init.js')
const wipeTables = require('../data/wipe.js')
const uuid = require('uuid/v4')
const request = require('supertest')
const dbConn = require('../data/dbConn.js')

beforeAll(async done => {
    await initTables()
    done()
})

afterAll(async done => {
    await wipeTables()
    await dbConn.destroy() //TODO: Remove the need for this by properly cleaning up database connections
    done()
})

test('successfully create a contact', async done => {
    const userId = uuid()
    const u1 = new User(userId)
    await u1.insert()
    const res = await request(app)
                        .post('/api/v1/contact')
                        .set('Accept', 'application/json')
                        .send({userUUID: u1.uuid, contact: {name: 'John Smith'}})
    expect(res.status).toBe(201)
    expect(res.body.errorFlag).toBe(0)
    expect(res.body.message.includes(u1.uuid)).toBe(true)
    expect(res.body.contact.name).toBe('John Smith')
    done()
})

test('fail to create a contact for a non-user', async done => {
    const res = await request(app)
                        .post('/api/v1/contact')
                        .set('Accept', 'application/json')
                        .send({contact: {name: 'John Smith'}})
    expect(res.status).toBe(400)
    expect(res.body.errorFlag).toBe(1)
    expect(res.body.message).toBe('Invalid user authorization')
    done()
})

test('fail to create a contact for a non-user', async done => {
    const userId = uuid()
    const u1 = new User(userId)
    await u1.insert()
    const res = await request(app)
                        .post('/api/v1/contact')
                        .set('Accept', 'application/json')
                        .send({userUUID: u1.uuid})
    expect(res.status).toBe(400)
    expect(res.body.errorFlag).toBe(1)
    expect(res.body.message).toBe('No contact data provided')
    done()
})

test('successfully update an existing contact', async done => {
    const userId = uuid()
    const u1 = new User(userId)
    await u1.insert()
    const insertedContactRes = await request(app)
                                        .post('/api/v1/contact')
                                        .set('Accept', 'application/json')
                                        .send({userUUID: u1.uuid, contact: {name: 'John Smith'}})
    const res = await request(app)
                        .put('/api/v1/contact')
                        .set('Accept', 'application/json')
                        .send({userUUID: u1.uuid, contact: {id: insertedContactRes.body.contact.id, relationship: 'father'}})
    expect(res.status).toBe(200)
    expect(res.body.errorFlag).toBe(0)
    expect(res.body.contact.id).toBe(insertedContactRes.body.id)
    expect(res.body.contact.name).toBe('John Smith')
    expect(res.body.contact.relationship).toBe('Father')
    done()
})

test('fail to update an non-existent contact', async done => {
    const userId = uuid()
    const u1 = new User(userId)
    await u1.insert()
    const insertedContactRes = await request(app)
                                        .post('/api/v1/contact')
                                        .set('Accept', 'application/json')
                                        .send({userUUID: u1.uuid, contact: {name: 'John Smith'}})
    const res = await request(app)
                        .put('/api/v1/contact')
                        .set('Accept', 'application/json')
                        .send({userUUID: u1.uuid, contact: {id: insertedContactRes.body.contact.id, relationship: 'father'}})
    expect(res.status).toBe(404)
    expect(res.body.errorFlag).toBe(1)
    expect(res.body.message).toBe('The supplied contact id does not exist')
    done()
})

test('fail to update a contact that doesn\'t belong to you', async done => {
    const userIdA = uuid(), userIdB=uuid()
    const u1 = new User(userIdA), u2 = new User(userIdB)
    await u1.insert()
    const insertedContactRes = await request(app)
                                        .post('/api/v1/contact')
                                        .set('Accept', 'application/json')
                                        .send({userUUID: u1.uuid, contact: {name: 'John Smith'}})
    const res = await request(app)
                        .put('/api/v1/contact')
                        .set('Accept', 'application/json')
                        .send({userUUID: u2.uuid, contact: {id: insertedContactRes.body.contact.id, relationship: 'father'}})
    expect(res.status).toBe(401)
    expect(res.body.errorFlag).toBe(1)
    expect(res.body.message).toBe('The supplied contact id does not belong to the given user')
    done()
})

